/**
 * Maintenance / Recovery utilities.
 *
 * These are manually-triggered admin tools. They are completely independent
 * of the production synchronization pipeline (importer, cron, activity
 * generation, stats). Nothing here runs automatically.
 *
 * Design principles:
 *   - User-agnostic. Active Hub users are ALWAYS resolved dynamically from
 *     the current database. No usernames, owners, or default pilots are
 *     hardcoded anywhere. There is NO fallback to any specific account.
 *   - Historical ownership is treated as immutable. When ownership cannot
 *     be resolved from historical data, the record is SKIPPED — never
 *     substituted with a current owner or another user.
 *   - Fully idempotent. All inserts go through
 *     `simfly_flights (username, flight_id)` uniqueness with
 *     `ignoreDuplicates: true`. Existing rows are never rewritten.
 *   - Modular. Additional utilities (Deep Recovery, SimFly API
 *     Verification, Repair Aircraft Revenue, Repair Pilot Career, Repair
 *     Airport Analytics) plug in through the same shared helpers.
 */
import { createServerFn } from "@tanstack/react-start";
import { createHash, timingSafeEqual } from "node:crypto";
// -------- Auth (mirrors admin.functions.ts) ---------------------------------
function checkToken(token: string | undefined): void {
  const expected = process.env.ADMIN_TOKEN;
  if (!expected) throw new Error("ADMIN_TOKEN is not configured on the server.");
  const a = createHash("sha256").update(String(token ?? ""), "utf8").digest();
  const b = createHash("sha256").update(expected, "utf8").digest();
  if (!timingSafeEqual(a, b)) throw new Error("Forbidden: invalid admin token.");
}
// -------- Shared types ------------------------------------------------------
export type RecoveryMode = "soft" | "flight";

export interface RecoveredItem {
  id: string;
  username: string;
  pilot: string;
  aircraft: string;
  tailNumber: string;
  route: string;
  at: string;
  delta: number;
}

export interface RecoveryReport {
  mode: RecoveryMode;
  windowDays: number;
  usersScanned: number;
  activitiesScanned: number;
  flightsScanned: number;
  missingActivities: number;
  recovered: number;
  alreadyCorrect: number;
  skipped: number;
  elapsedMs: number;
  notes: string[];
  recoveredItems: RecoveredItem[];
}

interface FlightRow {
  username: string;
  flight_id: string;
  aircraft_id: string | null;
  mission_start_ts: string | null;
  raw: Record<string, unknown>;
}
// -------- SimFly airplane-history lookup ------------------------------------
//
// The pilot-flight endpoint we already cache in `simfly_flights.raw` does NOT
// carry the aircraft-owner share (`raw.pax` there is the operating pilot's
// full flight income). Using that value verbatim on an owner Activity row
// would credit the aircraft owner with the pilot's full income, which is
// wrong — see SimFly's mission log ("Assets Rewards Generated by This Flight
// (All Owners)"): the aircraft owner only receives their per-flight rental
// share.
//
// The public airplane-history endpoint
//   GET /api/user/assets/airplane/{aircraftId}/flights?page=N
// returns the same flight objects with `airplane.totalEarnedPax` /
// `airplane.earnedPax` filled in — the same field the rest of the app already
// uses to display aircraft-owner income. We look up each recovery candidate
// there and use that value as the owner's delta. If a flight cannot be
// resolved this way, we SKIP it — never fall back to the pilot's PAX.
const SIMFLY_BASE = "https://simfly.io/api";
const OWNER_LOOKUP_MAX_PAGES = 40;
interface AirplaneHistFlight {
  flightID?: string;
  airplane?: { totalEarnedPax?: number; earnedPax?: number };
}
interface AirplaneHistPage {
  page?: number;
  itemPerPage?: number;
  flights?: AirplaneHistFlight[];
}
async function fetchSimflyJSON<T>(url: string): Promise<T | null> {
  try {
    const res = await fetch(url, { headers: { Accept: "application/json" } });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}
/**
 * Walk `/user/assets/airplane/{id}/flights` until every wanted flightID has
 * been matched or the pagination is exhausted. Returns a map
 * flightID → aircraft-owner share (in PAX). Missing flights are simply
 * absent from the map and MUST be skipped by the caller.
 */
async function loadOwnerSharesForAircraft(
  aircraftId: string,
  wantedIds: Set<string>,
): Promise<Map<string, number>> {
  const out = new Map<string, number>();
  const remaining = new Set(wantedIds);
  for (let p = 1; p <= OWNER_LOOKUP_MAX_PAGES && remaining.size > 0; p++) {
    const page = await fetchSimflyJSON<AirplaneHistPage>(
      `${SIMFLY_BASE}/user/assets/airplane/${encodeURIComponent(aircraftId)}/flights?page=${p}`,
    );
    const flights = page?.flights ?? [];
    if (!Array.isArray(flights) || flights.length === 0) break;
    for (const f of flights) {
      const id = f?.flightID;
      if (!id || !remaining.has(id)) continue;
      const share = f?.airplane?.totalEarnedPax ?? f?.airplane?.earnedPax ?? 0;
      const num = Number(share);
      if (Number.isFinite(num) && num >= 0) out.set(id, num);
      remaining.delete(id);
    }
    const perPage = page?.itemPerPage ?? flights.length;
    if (flights.length < perPage) break;
  }
  return out;
  }

// -------- Helpers -----------------------------------------------------------
/**
 * The set of "active Hub users" is derived from the backfill_progress table
 * (any pilot that has ever been imported into this Hub). This is the ONLY
 * source of truth. There are no hardcoded fallbacks.
 */
async function loadActiveHubUsers(supabaseAdmin: {
  from: (t: string) => {
    select: (c: string) => PromiseLike<{ data: { username: string }[] | null; error: { message?: string } | null }>;
  };
}): Promise<string[]> {
  const { data, error } = await supabaseAdmin
    .from("backfill_progress")
    .select("username");
  if (error) throw new Error(error.message ?? "Unable to load active Hub users.");
  const set = new Set<string>();
  for (const r of data ?? []) {
    const u = (r.username ?? "").trim();
    if (u) set.add(u);
  }
  return Array.from(set);
}
function isGenericAircraft(raw: Record<string, unknown>): boolean {
  const name = String((raw as { aircraft?: unknown }).aircraft ?? "").toLowerCase();
  if (!name) return true;
  if (name.includes("generic")) return true;
  if (name.includes("not in simfly")) return true;
  return false;
}
/**
 * Peer inference for historical aircraft ownership.
 *
 * We do NOT have per-flight owner data in the stored raw payload (SimFly's
 * pilot-flight endpoint does not include it) and we do NOT have a stored
 * historical-ownership table. Falling back to the aircraft's CURRENT owner
 * would violate the "historical records are immutable" rule.
 *
 * Instead, ownership is inferred from the same imported flight data:
 * for each aircraftId, the active Hub user with the largest count of
 * flights operating that aircraft is treated as the historical owner.
 * When the leading candidate is not clearly ahead, or the aircraft is
 * only flown by a single user (the operating pilot themselves),
 * ownership is UNRESOLVED and every flight for that aircraft is
 * SKIPPED. Never substituted.
 */
function inferOwnershipByAircraft(
  flights: FlightRow[],
  activeUsers: Set<string>,
): Map<string, string> {
  const counts = new Map<string, Map<string, number>>();
  for (const f of flights) {
    const aid = f.aircraft_id ?? "";
    if (!aid) continue;
    if (!activeUsers.has(f.username)) continue;
    let m = counts.get(aid);
    if (!m) {
      m = new Map();
      counts.set(aid, m);
    }
    m.set(f.username, (m.get(f.username) ?? 0) + 1);
  }
  const owners = new Map<string, string>();
  for (const [aid, m] of counts) {
    let best: string | null = null;
    let bestN = 0;
    let second = 0;
    for (const [u, n] of m) {
      if (n > bestN) {
        second = bestN;
        bestN = n;
        best = u;
      } else if (n > second) {
        second = n;
      }
    }
    // Require a clear plurality: at least 3 flights AND at least 2x the
    // runner-up. This avoids treating an occasional renter as the owner.
    if (best && bestN >= 3 && bestN >= second * 2) {
      owners.set(aid, best);
    }
  }
  return owners;
}
async function loadFlightsInWindow(
  supabaseAdmin: {
    from: (t: string) => {
      select: (c: string) => {
        gte: (col: string, v: string) => PromiseLike<{
          data: FlightRow[] | null;
          error: { message?: string } | null;
        }>;
      };
    };
  },
  windowDays: number,
): Promise<FlightRow[]> {
  const since = new Date(Date.now() - windowDays * 86400_000).toISOString();
  const { data, error } = await supabaseAdmin
    .from("simfly_flights")
    .select("username, flight_id, aircraft_id, mission_start_ts, raw")
    .gte("mission_start_ts", since);
  if (error) throw new Error(error.message ?? "Unable to load flights.");
  return (data ?? []).filter((r) => r && r.flight_id);
}
/**
 * Core recovery routine, shared by every mode. Given a scan window and a
 * `mode` label used in the report, walks every flight, resolves aircraft
 * ownership from historical data, and inserts any missing owner rows.
 *
 * Idempotency: inserts go through `simfly_flights` unique key
 * `(username, flight_id)` with `ignoreDuplicates: true`. Existing rows
 * are NEVER updated.
 */
async function runRecoveryCore(
  mode: RecoveryMode,
  windowDays: number,
): Promise<RecoveryReport> {
  const started = Date.now();
  const notes: string[] = [];
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const activeUsers = new Set(await loadActiveHubUsers(supabaseAdmin as never));
  if (activeUsers.size === 0) {
    return {
      mode,
      windowDays,
      usersScanned: 0,
      activitiesScanned: 0,
      flightsScanned: 0,
      missingActivities: 0,
      recovered: 0,
      alreadyCorrect: 0,
      skipped: 0,
      elapsedMs: Date.now() - started,
      notes: ["No active Hub users found."],
      recoveredItems: [],
    };
  }
  const flights = await loadFlightsInWindow(supabaseAdmin as never, windowDays);
  const owners = inferOwnershipByAircraft(flights, activeUsers);
  // Build a fast lookup for existing (username, flight_id) coverage.
  const existing = new Set<string>();
  for (const f of flights) existing.add(`${f.username}\u0000${f.flight_id}`);
  let activitiesScanned = 0;
  let flightsScanned = 0;
  let missing = 0;
  let recovered = 0;
  let alreadyCorrect = 0;
  let skipped = 0;
  // First pass: build the list of candidate owner rows purely from local
  // data (ownership inference + duplicate detection). We do NOT decide the
  // final `pax` here — the pilot payload does not contain the aircraft-owner
  // share, so we look that up from SimFly in a second pass.
  type Candidate = {
    owner: string;
    flight: FlightRow;
    aircraftName: string | null;
    departureIcao: string | null;
    destinationIcao: string | null;
    tailNumber: string;
  };
  const candidates: Candidate[] = [];
  for (const f of flights) {
    activitiesScanned++;
    if (!f.aircraft_id) { skipped++; continue; }
    if (isGenericAircraft(f.raw ?? {})) { skipped++; continue; }
    if (!activeUsers.has(f.username)) { skipped++; continue; }
    flightsScanned++;
    const owner = owners.get(f.aircraft_id);
    if (!owner) { skipped++; continue; }
    if (!activeUsers.has(owner)) { skipped++; continue; }
    if (owner === f.username) {
   // Operating pilot IS the owner: no owner activity needed.
      continue;
    }
    const key = `${owner}\u0000${f.flight_id}`;
    if (existing.has(key)) {
      alreadyCorrect++;
      continue;
    }
    missing++;
   const raw = f.raw ?? {};
   
    candidates.push({
      owner,
      flight: f,
      aircraftName: (raw as { aircraft?: string }).aircraft ?? null,
      departureIcao: (raw as { departure_icao?: string }).departure_icao ?? null,
      destinationIcao: (raw as { destination_icao?: string }).destination_icao ?? null,
      tailNumber:
        (raw as { tail_number?: string }).tail_number ??
        (raw as { tailNumber?: string }).tailNumber ??
        (raw as { registration?: string }).registration ??
        "",
    });
  }
  // Second pass: resolve the aircraft-owner share for every candidate flight
  // from SimFly's airplane-history endpoint. Group by aircraft_id so we make
  // at most one paginated walk per aircraft.
  const wantedByAircraft = new Map<string, Set<string>>();
  for (const c of candidates) {
    const aid = c.flight.aircraft_id!;
    let s = wantedByAircraft.get(aid);
    if (!s) { s = new Set(); wantedByAircraft.set(aid, s); }
    s.add(c.flight.flight_id);
  }
  const ownerShareByFlight = new Map<string, number>();
  for (const [aid, ids] of wantedByAircraft) {
    const found = await loadOwnerSharesForAircraft(aid, ids);
    for (const [fid, share] of found) ownerShareByFlight.set(fid, share);
  }
  const resolvedForAircraft = new Set(wantedByAircraft.keys());
  const unresolvedAircraft: string[] = [];
  for (const aid of resolvedForAircraft) {
    const asked = wantedByAircraft.get(aid)!.size;
    let got = 0;
    for (const fid of wantedByAircraft.get(aid)!) if (ownerShareByFlight.has(fid)) got++;
    if (got === 0) unresolvedAircraft.push(aid);
    else if (got < asked) notes.push(`Aircraft ${aid}: owner share resolved for ${got}/${asked} flights.`);
  }
  if (unresolvedAircraft.length > 0) {
    notes.push(`Owner share unresolved for ${unresolvedAircraft.length} aircraft — those flights were skipped.`);
  }
  const toInsert: Record<string, unknown>[] = [];
  const candidateItems: RecoveredItem[] = [];
  for (const c of candidates) {
    const share = ownerShareByFlight.get(c.flight.flight_id);
    if (share === undefined) {
      // Aircraft-owner share unknown → SKIP. Never fall back to the pilot's
      // full PAX; that would credit the owner with the pilot's income.
      skipped++;
      missing--; // this candidate is no longer counted as recoverable
      continue;
    }
    const ownerPax = Math.round(share * 100) / 100;
    const raw = { ...(c.flight.raw ?? {}) } as Record<string, unknown>;
    // Rewrite the persisted raw so downstream activity generation (which
    // reads `raw.pax` as the flight PAX) reflects the owner share, not the
    // pilot's income. Preserve everything else verbatim.
    raw.pax = ownerPax;

    toInsert.push({
      username: c.owner,
      flight_id: c.flight.flight_id,
      aircraft_id: c.flight.aircraft_id,
      aircraft: c.aircraftName,
      aircraft_icao: (raw as { aircraft_icao?: string }).aircraft_icao ?? null,
      destination_name: (raw as { destination?: { name?: string } }).destination?.name ?? null,
        destination_icao: c.destinationIcao,
      origin_name: (raw as { origin?: { name?: string } }).origin?.name ?? null,
         departure_icao: c.departureIcao,
      landing_rate: (raw as { landing_rate?: number }).landing_rate ?? null,
      total_distance: (raw as { total_distance?: number }).total_distance ?? null,
      flight_time: (raw as { flight_time?: string }).flight_time ?? null,
      // total_reward describes the operating pilot's full flight payout and
      // is NOT the aircraft owner's income. Do not copy it onto the owner
      // row — leave it null so no report mistakes it for owner revenue.
      total_reward: null,
      pax: ownerPax,
      xp: null,
      licence: null,
      licence_rank: null,
      licence_rank_name: null,
      mission_start_ts: c.flight.mission_start_ts,
      raw,
    });
   candidateItems.push({
      id: `${c.owner}:${c.flight.flight_id}`,
      username: c.owner,
      pilot: c.flight.username,
      aircraft: c.aircraftName ?? "Unknown Aircraft",
      tailNumber: String(c.tailNumber ?? ""),
      route: `${c.departureIcao ?? "----"} → ${c.destinationIcao ?? "----"}`,
      at: c.flight.mission_start_ts ?? "",
      delta: ownerPax,
    });
  }
  const recoveredItems: RecoveredItem[] = [];
  if (toInsert.length > 0) {
    const CHUNK = 200;
    for (let i = 0; i < toInsert.length; i += CHUNK) {
      const chunk = toInsert.slice(i, i + CHUNK);
      const items = candidateItems.slice(i, i + CHUNK);
      const { error } = await (supabaseAdmin as unknown as {
        from: (t: string) => {
          upsert: (v: unknown, o?: { onConflict?: string; ignoreDuplicates?: boolean }) => PromiseLike<{
            error: { message?: string } | null;
            count?: number | null;
          }>;
        };
      })
        .from("simfly_flights")
        .upsert(chunk, { onConflict: "username,flight_id", ignoreDuplicates: true });
      if (error) {
        notes.push(`Insert chunk failed: ${error.message ?? "unknown"}`);
        continue;
      }
      recovered += chunk.length;
      recoveredItems.push(...items);
    }
  }
  const usersScanned = new Set(flights.map((f) => f.username).filter((u) => activeUsers.has(u))).size;
  return {
    mode,
    windowDays,
    usersScanned,
    activitiesScanned,
    flightsScanned,
    missingActivities: missing,
    recovered,
    alreadyCorrect,
    skipped,
    elapsedMs: Date.now() - started,
    notes,
    recoveredItems,
  };
}
// -------- Public server functions ------------------------------------------
/**
 * Soft Recovery — reconstructs missing owner Activity entries from records
 * already present in the Activity view. Default 10-day window.
 */
export const runSoftRecovery = createServerFn({ method: "POST" })
  .inputValidator((d: { token: string; windowDays?: number }) => d)
  .handler(async ({ data }): Promise<RecoveryReport> => {
    checkToken(data.token);
    const w = Math.max(1, Math.min(90, data.windowDays ?? 10));
    return runRecoveryCore("soft", w);
  });
/**
 * Flight Recovery — inspects completed flight records directly (rather than
 * derived Activity rows) and creates any missing owner Activity entries.
 * Default 10-day window.
 */
export const runFlightRecovery = createServerFn({ method: "POST" })
  .inputValidator((d: { token: string; windowDays?: number }) => d)
  .handler(async ({ data }): Promise<RecoveryReport> => {
    checkToken(data.token);
    const w = Math.max(1, Math.min(90, data.windowDays ?? 10));
    return runRecoveryCore("flight", w);
  });
// -------- Reserved for future expansion ------------------------------------
//
// The following utilities are intentionally NOT implemented in Phase 1.
// When adding them, follow the same rules:
//   - resolve active Hub users dynamically
//   - never hardcode a username
//   - never overwrite historical ownership
//   - remain idempotent
//
//   export const runDeepRecovery       = createServerFn(...)  // Phase 2
//   export const runSimflyApiVerify    = createServerFn(...)  // Phase 2
//   export const runRepairAircraftRev  = createServerFn(...)  // Phase 3
//   export const runRepairPilotCareer  = createServerFn(...)  // Phase 3
//   export const runRepairAirportStats = createServerFn(...)  // Phase 3
