/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AirportsRouteImport } from './routes/airports'
import { Route as AircraftRouteImport } from './routes/aircraft'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersHandleRouteImport } from './routes/players.$handle'
import { Route as LicensesSlugRouteImport } from './routes/licenses.$slug'
import { Route as AirportsIdRouteImport } from './routes/airports.$id'
import { Route as AircraftIdRouteImport } from './routes/aircraft.$id'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportsRoute = AirportsRouteImport.update({
  id: '/airports',
  path: '/airports',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftRoute = AircraftRouteImport.update({
  id: '/aircraft',
  path: '/aircraft',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersHandleRoute = PlayersHandleRouteImport.update({
  id: '/players/$handle',
  path: '/players/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesSlugRoute = LicensesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LicensesRoute,
} as any)
const AirportsIdRoute = AirportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AirportsRoute,
} as any)
const AircraftIdRoute = AircraftIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AircraftRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/aircraft': typeof AircraftRouteWithChildren
  '/airports': typeof AirportsRouteWithChildren
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/licenses': typeof LicensesRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/stats': typeof StatsRoute
  '/aircraft/$id': typeof AircraftIdRoute
  '/airports/$id': typeof AirportsIdRoute
  '/licenses/$slug': typeof LicensesSlugRoute
  '/players/$handle': typeof PlayersHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/aircraft': typeof AircraftRouteWithChildren
  '/airports': typeof AirportsRouteWithChildren
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/licenses': typeof LicensesRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/stats': typeof StatsRoute
  '/aircraft/$id': typeof AircraftIdRoute
  '/airports/$id': typeof AirportsIdRoute
  '/licenses/$slug': typeof LicensesSlugRoute
  '/players/$handle': typeof PlayersHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/aircraft': typeof AircraftRouteWithChildren
  '/airports': typeof AirportsRouteWithChildren
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/licenses': typeof LicensesRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/stats': typeof StatsRoute
  '/aircraft/$id': typeof AircraftIdRoute
  '/airports/$id': typeof AirportsIdRoute
  '/licenses/$slug': typeof LicensesSlugRoute
  '/players/$handle': typeof PlayersHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/aircraft'
    | '/airports'
    | '/community'
    | '/compare'
    | '/licenses'
    | '/rankings'
    | '/stats'
    | '/aircraft/$id'
    | '/airports/$id'
    | '/licenses/$slug'
    | '/players/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/aircraft'
    | '/airports'
    | '/community'
    | '/compare'
    | '/licenses'
    | '/rankings'
    | '/stats'
    | '/aircraft/$id'
    | '/airports/$id'
    | '/licenses/$slug'
    | '/players/$handle'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/aircraft'
    | '/airports'
    | '/community'
    | '/compare'
    | '/licenses'
    | '/rankings'
    | '/stats'
    | '/aircraft/$id'
    | '/airports/$id'
    | '/licenses/$slug'
    | '/players/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AircraftRoute: typeof AircraftRouteWithChildren
  AirportsRoute: typeof AirportsRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  CompareRoute: typeof CompareRoute
  LicensesRoute: typeof LicensesRouteWithChildren
  RankingsRoute: typeof RankingsRoute
  StatsRoute: typeof StatsRoute
  PlayersHandleRoute: typeof PlayersHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airports': {
      id: '/airports'
      path: '/airports'
      fullPath: '/airports'
      preLoaderRoute: typeof AirportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft': {
      id: '/aircraft'
      path: '/aircraft'
      fullPath: '/aircraft'
      preLoaderRoute: typeof AircraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$handle': {
      id: '/players/$handle'
      path: '/players/$handle'
      fullPath: '/players/$handle'
      preLoaderRoute: typeof PlayersHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses/$slug': {
      id: '/licenses/$slug'
      path: '/$slug'
      fullPath: '/licenses/$slug'
      preLoaderRoute: typeof LicensesSlugRouteImport
      parentRoute: typeof LicensesRoute
    }
    '/airports/$id': {
      id: '/airports/$id'
      path: '/$id'
      fullPath: '/airports/$id'
      preLoaderRoute: typeof AirportsIdRouteImport
      parentRoute: typeof AirportsRoute
    }
    '/aircraft/$id': {
      id: '/aircraft/$id'
      path: '/$id'
      fullPath: '/aircraft/$id'
      preLoaderRoute: typeof AircraftIdRouteImport
      parentRoute: typeof AircraftRoute
    }
  }
}

interface AircraftRouteChildren {
  AircraftIdRoute: typeof AircraftIdRoute
}

const AircraftRouteChildren: AircraftRouteChildren = {
  AircraftIdRoute: AircraftIdRoute,
}

const AircraftRouteWithChildren = AircraftRoute._addFileChildren(
  AircraftRouteChildren,
)

interface AirportsRouteChildren {
  AirportsIdRoute: typeof AirportsIdRoute
}

const AirportsRouteChildren: AirportsRouteChildren = {
  AirportsIdRoute: AirportsIdRoute,
}

const AirportsRouteWithChildren = AirportsRoute._addFileChildren(
  AirportsRouteChildren,
)

interface LicensesRouteChildren {
  LicensesSlugRoute: typeof LicensesSlugRoute
}

const LicensesRouteChildren: LicensesRouteChildren = {
  LicensesSlugRoute: LicensesSlugRoute,
}

const LicensesRouteWithChildren = LicensesRoute._addFileChildren(
  LicensesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AircraftRoute: AircraftRouteWithChildren,
  AirportsRoute: AirportsRouteWithChildren,
  CommunityRoute: CommunityRoute,
  CompareRoute: CompareRoute,
  LicensesRoute: LicensesRouteWithChildren,
  RankingsRoute: RankingsRoute,
  StatsRoute: StatsRoute,
  PlayersHandleRoute: PlayersHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
